# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/bd/cpu_design/ip/cpu_design_thinpad_qusim_0_0/cpu_design_thinpad_qusim_0_0.xci
# IP: The module: 'cpu_design_thinpad_qusim_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/bd/cpu_design/ip/cpu_design_thinpad_qusim_0_0/src/floating_point_0/floating_point_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==floating_point_0 || ORIG_REF_NAME==floating_point_0} -quiet] -quiet

# IP: c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/bd/cpu_design/ip/cpu_design_thinpad_qusim_0_0/src/floating_point_4/floating_point_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==floating_point_4 || ORIG_REF_NAME==floating_point_4} -quiet] -quiet

# IP: C:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/bd/cpu_design/ip/cpu_design_thinpad_qusim_0_0/cpu_design_thinpad_qusim_0_0.xci
# IP: The module: 'cpu_design_thinpad_qusim_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/bd/cpu_design/ip/cpu_design_thinpad_qusim_0_0/src/floating_point_0/floating_point_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==floating_point_0 || ORIG_REF_NAME==floating_point_0} -quiet] -quiet

# IP: c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/bd/cpu_design/ip/cpu_design_thinpad_qusim_0_0/src/floating_point_4/floating_point_4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==floating_point_4 || ORIG_REF_NAME==floating_point_4} -quiet] -quiet
