# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/gjz010/Documents/GitHub/ip_repo/thinpad_qusim_1.0/src/floating_point_4/floating_point_4.xci
# IP: The module: 'floating_point_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gjz010/Documents/GitHub/ip_repo/thinpad_qusim_1.0/src/floating_point_4/floating_point_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_4'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/gjz010/Documents/GitHub/ip_repo/thinpad_qusim_1.0/src/floating_point_4/floating_point_4.xci
# IP: The module: 'floating_point_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gjz010/Documents/GitHub/ip_repo/thinpad_qusim_1.0/src/floating_point_4/floating_point_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
