# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/ip/cache_tag_store/cache_tag_store.xci
# IP: The module: 'cache_tag_store' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/ip/cache_tag_store/cache_tag_store_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cache_tag_store'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/ip/cache_tag_store/cache_tag_store.xci
# IP: The module: 'cache_tag_store' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/ip/cache_tag_store/cache_tag_store_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cache_tag_store'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
