# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/thinpad_top.xdc

# Block Designs: bd/cpu_design/cpu_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_design || ORIG_REF_NAME==cpu_design} -quiet] -quiet

# IP: bd/cpu_design/ip/cpu_design_rob_0_0/cpu_design_rob_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_design_rob_0_0 || ORIG_REF_NAME==cpu_design_rob_0_0} -quiet] -quiet

# IP: bd/cpu_design/ip/cpu_design_renamebuffer_0_0/cpu_design_renamebuffer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_design_renamebuffer_0_0 || ORIG_REF_NAME==cpu_design_renamebuffer_0_0} -quiet] -quiet

# IP: bd/cpu_design/ip/cpu_design_reservestation_0_0/cpu_design_reservestation_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_design_reservestation_0_0 || ORIG_REF_NAME==cpu_design_reservestation_0_0} -quiet] -quiet

# IP: bd/cpu_design/ip/cpu_design_dispatcher_0_0/cpu_design_dispatcher_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_design_dispatcher_0_0 || ORIG_REF_NAME==cpu_design_dispatcher_0_0} -quiet] -quiet

# IP: bd/cpu_design/ip/cpu_design_registers_0_0/cpu_design_registers_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_design_registers_0_0 || ORIG_REF_NAME==cpu_design_registers_0_0} -quiet] -quiet

# IP: bd/cpu_design/ip/cpu_design_pc_counter_0_0/cpu_design_pc_counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_design_pc_counter_0_0 || ORIG_REF_NAME==cpu_design_pc_counter_0_0} -quiet] -quiet

# IP: bd/cpu_design/ip/cpu_design_decoder_0_0/cpu_design_decoder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_design_decoder_0_0 || ORIG_REF_NAME==cpu_design_decoder_0_0} -quiet] -quiet

# IP: bd/cpu_design/ip/cpu_design_if_tlb_fetcher_0_0/cpu_design_if_tlb_fetcher_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_design_if_tlb_fetcher_0_0 || ORIG_REF_NAME==cpu_design_if_tlb_fetcher_0_0} -quiet] -quiet

# IP: bd/cpu_design/ip/cpu_design_if_memory_accessor_0_0/cpu_design_if_memory_accessor_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_design_if_memory_accessor_0_0 || ORIG_REF_NAME==cpu_design_if_memory_accessor_0_0} -quiet] -quiet

# IP: bd/cpu_design/ip/cpu_design_if_insn_queue_0_0/cpu_design_if_insn_queue_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_design_if_insn_queue_0_0 || ORIG_REF_NAME==cpu_design_if_insn_queue_0_0} -quiet] -quiet

# IP: bd/cpu_design/ip/cpu_design_jump_predictor_0_0/cpu_design_jump_predictor_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_design_jump_predictor_0_0 || ORIG_REF_NAME==cpu_design_jump_predictor_0_0} -quiet] -quiet

# IP: bd/cpu_design/ip/cpu_design_branch_predictor_0_1/cpu_design_branch_predictor_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_design_branch_predictor_0_1 || ORIG_REF_NAME==cpu_design_branch_predictor_0_1} -quiet] -quiet

# IP: bd/cpu_design/ip/cpu_design_if_controller_0_0/cpu_design_if_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_design_if_controller_0_0 || ORIG_REF_NAME==cpu_design_if_controller_0_0} -quiet] -quiet

# IP: bd/cpu_design/ip/cpu_design_loadstoreunit_0_0/cpu_design_loadstoreunit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_design_loadstoreunit_0_0 || ORIG_REF_NAME==cpu_design_loadstoreunit_0_0} -quiet] -quiet

# IP: bd/cpu_design/ip/cpu_design_clk_wiz_0_1/cpu_design_clk_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_design_clk_wiz_0_1 || ORIG_REF_NAME==cpu_design_clk_wiz_0_1} -quiet] -quiet

# IP: bd/cpu_design/ip/cpu_design_proc_sys_reset_0_0/cpu_design_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_design_proc_sys_reset_0_0 || ORIG_REF_NAME==cpu_design_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/cpu_design/ip/cpu_design_axi_simple_master_0_0/cpu_design_axi_simple_master_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_design_axi_simple_master_0_0 || ORIG_REF_NAME==cpu_design_axi_simple_master_0_0} -quiet] -quiet

# IP: bd/cpu_design/ip/cpu_design_axi_simple_master_0_1/cpu_design_axi_simple_master_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_design_axi_simple_master_0_1 || ORIG_REF_NAME==cpu_design_axi_simple_master_0_1} -quiet] -quiet

# IP: bd/cpu_design/ip/cpu_design_axi_simple_master_0_2/cpu_design_axi_simple_master_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_design_axi_simple_master_0_2 || ORIG_REF_NAME==cpu_design_axi_simple_master_0_2} -quiet] -quiet

# IP: bd/cpu_design/ip/cpu_design_l1_cache_0_0/cpu_design_l1_cache_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_design_l1_cache_0_0 || ORIG_REF_NAME==cpu_design_l1_cache_0_0} -quiet] -quiet

# IP: bd/cpu_design/ip/cpu_design_loadstore_functionun_0_0/cpu_design_loadstore_functionun_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_design_loadstore_functionun_0_0 || ORIG_REF_NAME==cpu_design_loadstore_functionun_0_0} -quiet] -quiet

# IP: bd/cpu_design/ip/cpu_design_axi_bram_ctrl_1_0/cpu_design_axi_bram_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_design_axi_bram_ctrl_1_0 || ORIG_REF_NAME==cpu_design_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: bd/cpu_design/ip/cpu_design_blk_mem_gen_1_0/cpu_design_blk_mem_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_design_blk_mem_gen_1_0 || ORIG_REF_NAME==cpu_design_blk_mem_gen_1_0} -quiet] -quiet

# IP: bd/cpu_design/ip/cpu_design_thinpad_sram_0_0/cpu_design_thinpad_sram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_design_thinpad_sram_0_0 || ORIG_REF_NAME==cpu_design_thinpad_sram_0_0} -quiet] -quiet

# IP: bd/cpu_design/ip/cpu_design_xbar_0/cpu_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_design_xbar_0 || ORIG_REF_NAME==cpu_design_xbar_0} -quiet] -quiet

# IP: bd/cpu_design/ip/cpu_design_axi_interconnect_0_0/cpu_design_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_design_axi_interconnect_0_0 || ORIG_REF_NAME==cpu_design_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/cpu_design/ip/cpu_design_axi_intc_0_0/cpu_design_axi_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_design_axi_intc_0_0 || ORIG_REF_NAME==cpu_design_axi_intc_0_0} -quiet] -quiet

# IP: bd/cpu_design/ip/cpu_design_axi_gpio_0_1/cpu_design_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_design_axi_gpio_0_1 || ORIG_REF_NAME==cpu_design_axi_gpio_0_1} -quiet] -quiet

# IP: bd/cpu_design/ip/cpu_design_thinpad_serial_0_0/cpu_design_thinpad_serial_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_design_thinpad_serial_0_0 || ORIG_REF_NAME==cpu_design_thinpad_serial_0_0} -quiet] -quiet

# IP: bd/cpu_design/ip/cpu_design_xlconcat_0_0/cpu_design_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_design_xlconcat_0_0 || ORIG_REF_NAME==cpu_design_xlconcat_0_0} -quiet] -quiet

# IP: bd/cpu_design/ip/cpu_design_auto_ds_0/cpu_design_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_design_auto_ds_0 || ORIG_REF_NAME==cpu_design_auto_ds_0} -quiet] -quiet

# IP: bd/cpu_design/ip/cpu_design_auto_pc_0/cpu_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_design_auto_pc_0 || ORIG_REF_NAME==cpu_design_auto_pc_0} -quiet] -quiet

# IP: bd/cpu_design/ip/cpu_design_auto_ds_1/cpu_design_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_design_auto_ds_1 || ORIG_REF_NAME==cpu_design_auto_ds_1} -quiet] -quiet

# IP: bd/cpu_design/ip/cpu_design_auto_pc_1/cpu_design_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_design_auto_pc_1 || ORIG_REF_NAME==cpu_design_auto_pc_1} -quiet] -quiet

# IP: bd/cpu_design/ip/cpu_design_auto_pc_2/cpu_design_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_design_auto_pc_2 || ORIG_REF_NAME==cpu_design_auto_pc_2} -quiet] -quiet

# IP: bd/cpu_design/ip/cpu_design_s00_mmu_0/cpu_design_s00_mmu_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_design_s00_mmu_0 || ORIG_REF_NAME==cpu_design_s00_mmu_0} -quiet] -quiet

# IP: bd/cpu_design/ip/cpu_design_s01_mmu_0/cpu_design_s01_mmu_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_design_s01_mmu_0 || ORIG_REF_NAME==cpu_design_s01_mmu_0} -quiet] -quiet

# XDC: bd/cpu_design/cpu_design_ooc.xdc
