# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a100tfgg676-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.cache/wt [current_project]
set_property parent.project_path C:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  c:/Users/gjz010/Documents/GitHub/ip_repo/thinpad_qusim_1.0
  c:/Users/gjz010/Documents/GitHub/ip_repo/thinpad_serial_1.0
  c:/Users/gjz010/Documents/GitHub/ip_repo/simple_axilite_slave_1.0
  c:/Users/gjz010/Documents/GitHub/ip_repo/axi_simple_master_1.0
  c:/Users/gjz010/Documents/GitHub/ip_repo/l1_cache_1.0
  c:/Users/gjz010/Documents/GitHub/ip_repo/sram_1.0
  c:/Users/gjz010/Documents/GitHub/ip_repo/thinpad_sram_1.0
  c:/Users/gjz010/Documents/GitHub/qsim_compiler_coprocessor
  c:/Users/gjz010/Documents/GitHub/ip_repo/systolic_1.0
  c:/links/qsim
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/bd/cpu_design/ip/qurisc_rom.coe
read_verilog C:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/new/defs.vh
set_property is_global_include true [get_files C:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/new/defs.vh]
read_verilog -library xil_defaultlib {
  C:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/bd/cpu_design/hdl/cpu_design_wrapper.v
  C:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/new/vga.v
  C:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/new/thinpad_top.v
}
add_files C:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/bd/cpu_design/cpu_design.bd
set_property used_in_implementation false [get_files -all c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/bd/cpu_design/ip/cpu_design_clk_wiz_0_1/cpu_design_clk_wiz_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/bd/cpu_design/ip/cpu_design_clk_wiz_0_1/cpu_design_clk_wiz_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/bd/cpu_design/ip/cpu_design_clk_wiz_0_1/cpu_design_clk_wiz_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/bd/cpu_design/ip/cpu_design_proc_sys_reset_0_0/cpu_design_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/bd/cpu_design/ip/cpu_design_proc_sys_reset_0_0/cpu_design_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/bd/cpu_design/ip/cpu_design_proc_sys_reset_0_0/cpu_design_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/bd/cpu_design/ip/cpu_design_axi_bram_ctrl_1_0/cpu_design_axi_bram_ctrl_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/bd/cpu_design/ip/cpu_design_blk_mem_gen_1_0/cpu_design_blk_mem_gen_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/bd/cpu_design/ip/cpu_design_xbar_0/cpu_design_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/bd/cpu_design/ip/cpu_design_axi_intc_0_0/cpu_design_axi_intc_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/bd/cpu_design/ip/cpu_design_axi_intc_0_0/cpu_design_axi_intc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/bd/cpu_design/ip/cpu_design_axi_intc_0_0/cpu_design_axi_intc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/bd/cpu_design/ip/cpu_design_axi_gpio_0_1/cpu_design_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/bd/cpu_design/ip/cpu_design_axi_gpio_0_1/cpu_design_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/bd/cpu_design/ip/cpu_design_axi_gpio_0_1/cpu_design_axi_gpio_0_1.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/bd/cpu_design/ip/cpu_design_auto_ds_0/cpu_design_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/bd/cpu_design/ip/cpu_design_auto_ds_0/cpu_design_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/bd/cpu_design/ip/cpu_design_auto_ds_0/cpu_design_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/bd/cpu_design/ip/cpu_design_auto_pc_0/cpu_design_auto_pc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/bd/cpu_design/ip/cpu_design_auto_ds_1/cpu_design_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/bd/cpu_design/ip/cpu_design_auto_ds_1/cpu_design_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/bd/cpu_design/ip/cpu_design_auto_ds_1/cpu_design_auto_ds_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/bd/cpu_design/ip/cpu_design_auto_pc_1/cpu_design_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/bd/cpu_design/ip/cpu_design_auto_pc_2/cpu_design_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/bd/cpu_design/ip/cpu_design_auto_pc_3/cpu_design_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/bd/cpu_design/ip/cpu_design_s00_mmu_0/cpu_design_s00_mmu_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/bd/cpu_design/ip/cpu_design_s01_mmu_0/cpu_design_s01_mmu_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/bd/cpu_design/cpu_design_ooc.xdc]

read_ip -quiet C:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/ip/pll_example/pll_example.xci
set_property used_in_implementation false [get_files -all c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/ip/pll_example/pll_example_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/ip/pll_example/pll_example.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/ip/pll_example/pll_example_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/constrs_1/new/thinpad_top.xdc
set_property used_in_implementation false [get_files C:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/constrs_1/new/thinpad_top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top thinpad_top -part xc7a100tfgg676-2L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef thinpad_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file thinpad_top_utilization_synth.rpt -pb thinpad_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
