# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL-1065} -limit 10000
set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7a100tfgg676-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.cache/wt [current_project]
set_property parent.project_path C:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  c:/Users/gjz010/Documents/GitHub/ip_repo/simple_axilite_slave_1.0
  c:/Users/gjz010/Documents/GitHub/ip_repo/axi_simple_master_1.0
  c:/Users/gjz010/Documents/GitHub/ip_repo/l1_cache_1.0
  c:/Users/gjz010/Documents/GitHub/ip_repo/sram_1.0
  c:/Users/gjz010/Documents/GitHub/ip_repo/thinpad_sram_1.0
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/ip/cache_block/cache_block.xci
set_property used_in_implementation false [get_files -all c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/ip/cache_block/cache_block_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

set cached_ip [config_ip_cache -export -no_bom  -dir C:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.runs/cache_block_synth_1 -new_name cache_block -ip [get_ips cache_block]]

if { $cached_ip eq {} } {
close [open __synthesis_is_running__ w]

synth_design -top cache_block -part xc7a100tfgg676-2L -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
# disable binary constraint mode for IPCache checkpoints
set_param constraints.enableBinaryConstraints false

catch {
 write_checkpoint -force -noxdef -rename_prefix cache_block_ cache_block.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ cache_block_stub.v
 lappend ipCachedFiles cache_block_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ cache_block_stub.vhdl
 lappend ipCachedFiles cache_block_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ cache_block_sim_netlist.v
 lappend ipCachedFiles cache_block_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ cache_block_sim_netlist.vhdl
 lappend ipCachedFiles cache_block_sim_netlist.vhdl
set TIME_taken [expr [clock seconds] - $TIME_start]

 config_ip_cache -add -dcp cache_block.dcp -move_files $ipCachedFiles -use_project_ipc  -synth_runtime $TIME_taken  -ip [get_ips cache_block]
}

rename_ref -prefix_all cache_block_

# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef cache_block.dcp
create_report "cache_block_synth_1_synth_report_utilization_0" "report_utilization -file cache_block_utilization_synth.rpt -pb cache_block_utilization_synth.pb"

if { [catch {
  file copy -force C:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.runs/cache_block_synth_1/cache_block.dcp c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/ip/cache_block/cache_block.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/ip/cache_block/cache_block_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/ip/cache_block/cache_block_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/ip/cache_block/cache_block_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/ip/cache_block/cache_block_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force C:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.runs/cache_block_synth_1/cache_block.dcp c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/ip/cache_block/cache_block.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force C:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.runs/cache_block_synth_1/cache_block_stub.v c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/ip/cache_block/cache_block_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.runs/cache_block_synth_1/cache_block_stub.vhdl c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/ip/cache_block/cache_block_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.runs/cache_block_synth_1/cache_block_sim_netlist.v c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/ip/cache_block/cache_block_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.runs/cache_block_synth_1/cache_block_sim_netlist.vhdl c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/ip/cache_block/cache_block_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir C:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.ip_user_files/ip/cache_block]} {
  catch { 
    file copy -force c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/ip/cache_block/cache_block_stub.v C:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.ip_user_files/ip/cache_block
  }
}

if {[file isdir C:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.ip_user_files/ip/cache_block]} {
  catch { 
    file copy -force c:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.srcs/sources_1/ip/cache_block/cache_block_stub.vhdl C:/Users/gjz010/Documents/GitHub/thinpad_top/thinpad_top.ip_user_files/ip/cache_block
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
